### ISSUE TITLE
No carriage return after </gpx> causes issues with Geosetter

### ISSUE THREAD

**Issue by AnotherKiwiEater** [BasicAirData/GPSLogger#113]
I have been using Geosetter extensively and noticed that recently I was not able to use the GPS Logger gpx exports as imports directly as they were not recognized until I added a carriage return at the end of the files </gpx>.  Since Geosetter has not be getting recent updates, I could continue to edit the gpx files before importing, but I suggest if GPS Logger could add a carriage return after </gpx> and before the end of file, it would solve the import issue.

**Comment by GrazianoCapelli** [comment]
Hi,
Fist of all, thanks for opening the Issue and for make us informed of this Problem.

As a general note: After every modification on the Exporter code, We check the new KML/GPX output with ([Apache Xerces](https://xerces.apache.org/)). We are careful to export files 100% compatible with the GPX and KML standards. In fact the GPX exported by v2.2.10 (and also by the previous versions) passes the validation Test.

In spite of this, some Application could still have Problems due to Limitations in importation.
In this case we are glad to modify our exporter in order to solve the Problem (remaining into the standard).

The GPS Logger v2.3.0 will fix this issue, please be patient some Weeks.

_In the meanwhile, if you want, I suggest to report the misbehaviour also to Geosetter's team, in order to make them aware of it too.
In fact Geosetter doesn't open a 100% valid GPX file, and this misbehaviour could cause compatibility Problems between Geosetter and other Apps._

**Comment by GrazianoCapelli** [comment]
Today we published the new App's update, including the carriage return at the end of the GPX files.
With GPS Logger v2.3.0 my GPX files are imported into Geosetter 3.5.3 (build 2195) without problems.

Please update GPS Logger and try with your Geosetter too, in order to verify that the problem is solved.
We would be glad to receive the feedback of your test.
