### ISSUE TITLE
Exported GPX files are truncated at the end

### ISSUE THREAD

**Issue by drugstorer-172** [BasicAirData/GPSLogger#118]
I want to import the placemarks file saved in GPS Logger by Exportfunction as a gpx file into QGIS 3.16 Hannover.
When I import I always get the errormessage: "Cannot find trk-tag in GPX file".
What is wrong? The track feature works properly.
[20201125-104856[2].txt](https://github.com/BasicAirData/GPSLogger/files/5596219/20201125-104856.2.txt)

**Comment by GrazianoCapelli** [comment]
I opened the file you enclosed, and I saw that the file is interrupted.
Did you cut it before the inclusion, or the exporter interrupted the exportation at that point?

**Comment by drugstorer-172** [comment]
Thanx Graziano

I did not change anything.
The file looks the same in other test.

**Comment by GrazianoCapelli** [comment]
Could you post the complete File please?

**Comment by drugstorer-172** [comment]
Sure. Here it is. Remove the txt part of the name
[20201125-104856[1].gpx.txt](https://github.com/BasicAirData/GPSLogger/files/5597052/20201125-104856.1.gpx.txt)

**Comment by GrazianoCapelli** [comment]
Ok. The file is not finished.
If I understand well, the exporter interrupted the exportation for some reason.

Assuming that the cause is not a lack of space in the device, I think that it could be due to a bad flushing of the `BufferedWriter` before the closure of the file. This case, to avoid it, we'll add an explicit call to the `flush` method at the end of the exportation in the next app's update.

Thanks for your feedback!

**Comment by drugstorer-172** [comment]
Thanx Graziano
Waiting for the update. I will test asap when update is available

**Comment by GrazianoCapelli** [comment]
@drugstorer-172 - GPS Logger v2.3.1 is out with the patch that should have fixed your issue with the exported files.
We would be grateful if you could make a new test and give us the feedback, because we were unable to replicate the problem on any of our test devices.

I closed the issue, but we are glad to reopen it in case the problem is still present.

**Comment by drugstorer-172** [comment]
@GrazianoCapelli 
I works. Perfect and Thanks. 👍
