### ISSUE TITLE
app keep stopping + lost all tracks

### ISSUE THREAD

**Issue by oluc** [BasicAirData/GPSLogger#119]
today GPSLogger is not working anymore. 

The home screen icon displays a default "Android" icon, named "eu.basicairdata.graziano.g..."

Trying to launch it displays a dialog "eu.basicairdata. (...) keeps stopping"

Apparently I lost all my tracks. 

(except a few in the GPSLogger folder)

The Android/data/eu.basicairdata.../ folder is empty

The last time I used it was on Nov. 20, IIRC.

It was last updated that day too, according to PlayStore
   "Last updated 20 Nov 2020"

Are my tracks completely lost?

Could it be due to the update? 
or something else?

**Comment by JLJu** [comment]
We have no reports about this misbehaviour. Can you post the error message/screenshot? Some file should be retained in GPSLogger\appdata folder.

**Comment by GrazianoCapelli** [comment]
> The home screen icon displays a default "Android" icon, named "eu.basicairdata.graziano.g..."

Basing on your description, I think that the issue has been caused by a Play Store error updating the app.
Unfortunately the update service is entirely managed by Google: we upload the new APK on the Store when we release an Update, but the update is scheduled and performed by the Google Play service.

I don't know what is your Computer Level, thus I'll try to list some suggestions:

1) **PREFERRED**: You can uninstall the app using the adb commands, and then reinstall using the play store: [Here](https://cmetcalfe.ca/blog/reinstall-android-app-without-losing-data.html) you can find an article. Not easy, but it should preserve your data.

2) As second suggestion you can download GPS Logger [here from this repo](https://github.com/BasicAirData/GPSLogger/blob/master/apk/GPSLogger-2.3.0.apk) and try to install it overwriting the Google Play existing one. But the method depends on manufacturer and Android Version.

3) Uninstall and install the app from the Play Store: the app will return to run, but I think this way you'll lose your data.

Hope it will help.

**Comment by oluc** [comment]
I did the reinstall with the prefered method, and GPSLogger is back with all my tracks.
So it seems something went wrong with PlayStore during the update.
**Thank you** so much for the instructions! and for GPSLogger, it's very useful to me

**Comment by GrazianoCapelli** [comment]
Glad it helped.
Thanks for your Feedback!
