### ISSUE TITLE
Tasker integration?

### ISSUE THREAD

**Issue by wwwald** [BasicAirData/GPSLogger#126]
Just bumped into this app after years of using [GPSLogger](https://github.com/mendhak/gpslogger) - which has sadly stopped development. One of its unique features is Tasker integration - for instance, I'm using it to automatically capture my car rides.

As far as I can see, it doesn't seem that GPS Logger offers Tasker integration yet, is that correct? Is this something that is somewhere on the roadmap?

**Comment by GrazianoCapelli** [comment]
Unfortunately GPS Logger doesn't have any integration with Tasker, and we don't have in plan to implement it.

The App you used was very different from ours: it was particularly focused on direct integration with remote services, with many interesting features for automatic exportation.

Conversely, We don't implement any direct integration with cloud services or third-part / commercial API, because we would to keep GPS logger as clean, light, and basic as possible.
As a result, all the exportation / sharing / on-map uploading operations are performed manually.

**Comment by wwwald** [comment]
OK, great to learn about your goals and specific roadmap, and thanks for the clear answer. Fully understand and respect your clear focus, will definitely help you in the long run!

**Comment by GrazianoCapelli** [comment]
I closed the issue to keep our issue tracker clean.
If you need, feel free to reopen it and add new comments.

**Comment by GrazianoCapelli** [comment]
@wwwald I would to inform you that we are implementing some shortcuts for the main Activity of GPS Logger, that maybe could be used also to drive the app with automation taskers.
We have in plan to assign a shortcut to the main actions of the activity, like record / pause recording, add annotations, stop and finalize the track, but we are open to discuss the implementation of additional shortcuts on user demand.

You can follow the implementation and discuss the specifications on #168.
