### ISSUE TITLE
Low speed filtering

### ISSUE THREAD

**Issue by matchumen** [BasicAirData/GPSLogger#127]
Hi, 

From what i found in code (`Track.java` `MOVEMENT_SPEED_THRESHOLD = 0.5f;`) the speed is recorded as zero, when GPS speed drops below 0.5. Despite that, when i calculated speed after the recording (using Haversine formula), I found, that even speeds above the threshold are zeroed. 

Is it caused by difference in speed calculation method or is there any other rule affecting the zeroing of the speed?

Thank you

**Comment by GrazianoCapelli** [comment]
Hi,
The speed that is acquired from the GPS (when available) is calculated by the GPS chipset and sent to the Apps together with FIX data.

As a general note, we prefer to record the GPS data _as is_ (without modification): for this reason we don't zero any speed.
We use this Speed on calculation only to determine if the user is still or in movement. The `MOVEMENT_SPEED_THRESHOLD` is the minimum value considered as movement, and this value influences the computation of the _Time in Movement_.
The App calculates the average speeds using Distance and Time.

If you experienced an (high) speed zeroing, it should be due to a particularly "generous" cut threshold of your GPS chipset.

**Comment by matchumen** [comment]
Thank you for the reply, I'll look into it.
