### ISSUE TITLE
Export tracks via API

### ISSUE THREAD

**Issue by TVEgit** [BasicAirData/GPSLogger#138]
Hi, I use VisuGPX, a French site for managing/preparing/sharing GPX tracks (www.visugpx.com). Unfortunately, it is for now only in French (API documentation is [here](https://www.visugpx.com/api/documentation_api.php)).
VisuGPX is only a WebApp and cannot record tracks. GPS Logger is a perfect companion to this site.
VisuGPX offers a web API allowing posting tracks onto a user account.
Here is an example call to post a GPX file :
`curl -X POST -H "Authorization: Bearer JFV7ZFhdJqwQZ28MVDN4hJOFo" -F "gpx=@\path\to\file.gpx" -F "name=Nom de la trace" -F "activity=vtt" "https://www.visugpx.com/api/upload"
`
VisuGPX lets a user get its own API key for security then authorize using Oauth2 scheme for integrating with third party apps and sites.

What would be the path for adding the capability to export GPX files from GPS Logger to VisuGPX or other similar sites using this kind of API?
- could there be a new standard feature included in GPS logger to let the user fill in API calls, keys etc.?
- should it require custom code to be added to the core GPS Logger codebase? In such case, could the developper of the VisuGPX web site contribute to writing this code?

Thank you.

**Comment by GrazianoCapelli** [comment]
First of all I thank you on behalf of the whole team for considering GPS Logger a good companion to your Website.

When we started to develop GPS Logger, we chosen to not integrate any APIs or accounts, in order to keep this app as free, maintainable, and light as possible. For this reason you don't find any direct integration with Dropbox, Google, or other Cloud services.
We instead prefer to provide a simple way to share the files using the standard Android sharing feature. Using it, the users can easily load their traces into a lot of platforms/Apps/Cloud services.
Not 100% automatic, but very simple and 100% user choice.
We intend to go straight with this developing philosophy.

Of course, GPS Logger is 100% open and free software: feel free to fork and use it to implement your features!
Here you can find our license: https://github.com/BasicAirData/GPSLogger/blob/master/LICENSE

**Comment by TVEgit** [comment]
Thank you for your answer. It makes sense. I agree about this choice, at least for now.
