### ISSUE TITLE
Unable to select OpenTopoMap as track viewer

### ISSUE THREAD

**Issue by andreytkachenko** [BasicAirData/GPSLogger#142]
I have chosen as default app for GPX in the system, and it perfectly works from any file manager - just click on a GPX file and it instanlty opens in OpenTopoMap, but I cannot select this app as default viewer for tracks in GPSLogger (it offers only Termux). In the settings I also cannot change it.

**Comment by GrazianoCapelli** [comment]
Dear Andrey,
As first note, GPS Logger doesn't use the Android default app to choose which viewer to use, but it has an internal setting instead that allow to choose among all the KML and GPX viewers.
We used it in the past, but we switch to a more direct solution because in general the users find the android defaults not user friendly to set, specially with 2 formats to manage (KML and GPX).

Ok, let's focus on the issue.
I tried to install _Skails OpenTopoMap Viewer_ (hoping you are referring to this app), and to test it with GPS Logger.
The app is present in GPS Logger on the list of available viewers:

![20210624_121200](https://user-images.githubusercontent.com/6907566/123246601-416a8a80-d4e6-11eb-8a85-6a807fdfc5b3.jpg)

Unfortunately I cannot test the track opening because when I launched OpenTopoMap from the Android menu (not from GPS Logger), the app opened with a hanging gray screen:

![20210624_122300](https://user-images.githubusercontent.com/6907566/123247454-36fcc080-d4e7-11eb-99f2-5dabd7b1b456.jpg)

I think the app could be relatively new (currently has less than 100 downloads on the store) and the developers could have yet someting to adjust. Or maybe my Samsung J3 with Android 8 is somehow incompatible with it...

Anyway, as second test I installed _Termux_ and I verified that it doesn't appear on the list.
In effect it doesn't.

As a start, Please specify which Android version you are using and what version of GPS Logger you are referring (I tested it with the v3.0.1). Furthermore, we would be glad to have a screenshot of the `Settings -> Track Viewer` list menu and of the tracklist with the actionbar visible, in order to make clear what is happening.

**Comment by andreytkachenko** [comment]
Firstly thank you for your detailed reply and your work on such usefull project. I have poco x3 nfc with custom (Arrow OS) android 11 installed. Version of GPSLogger is  v3.0.1. On F-Droid I have found only one properly-working GPX Viewer (If you know better please share) - https://f-droid.org/en/packages/org.nitri.opentopo/. And I cannot select neither from top icon nor from settings (maybe there are som secret, but I didn't found any way how to specify application for mime like `xdg-mime default` on linux.

**Comment by GrazianoCapelli** [comment]
@andreytkachenko I didn't know the existance of this great open source viewer, thank you for informing me.
I tested the viewer, in effect is not present on the GPS Logger viewer's list.
I contacted the developers of OpenTopoMap Viewer in order to solve the issue; you can follow the status of the issue by clicking the link here above.

**Comment by andreytkachenko** [comment]
Great! Thank you very much for so quick reply and intention to solve the issue, and fo not write something like "it is not GPSLogger problem".

**Comment by GrazianoCapelli** [comment]
The developer of OpenTopoMap Viewer releases the Version 1.11.6 (27), that should work well with GPS Logger.
We would be glad to receive a feedback of your test.

**Comment by andreytkachenko** [comment]
Can confirm - with latest update there are no more such problem. Thank you a lot for your help!
