### ISSUE TITLE
Can' find kml and gpx files on the device

### ISSUE THREAD

**Issue by user2155** [BasicAirData/GPSLogger#167]
It worked fine, but after latest updates export doesn't work anymore - there is no kml and gpx files in the directory "GPSLogger" or in any other. 
I can only access these files using "Share with" option (Bluetooth, Gmail, "Save to Drive").
If press button "Export" (the second button from the right), the Open File Dialog appears.
Can it be fixed?

I have Android 5.0.2

**Comment by GrazianoCapelli** [comment]
Starting from GPS Logger v3.1.0 the exportation folder is selectable (on Android 5+):
When you export a track for the first time, the dialog allows you to select the the local exportation folder.
You can keep using the old `/GPSLogger` folder by selecting it on the dialog, but you could choose to pick another destination.
It is possible to select (and to change) the local exportation folder also in the app Settings, Interface section, by clicking the "_Local Exportation Folder_" preference.

The selection of the folder is now mandatory because of a change on Google specifications, that restricted the permission to access the whole storage only in exceptional cases for privacy reasons. In fact, as you can see in Android system settings, GPS Logger no longer needs the Storage permission, because the access to the storage is limited to the folder you selected.

_As a note, some special folders (like the root folders, or the Downloads) could be not suitable for the exportation, depending on the Android version. In this case please select another (sub)folder, or create a new one._

I hope it helps.

**Comment by user2155** [comment]
> Starting from GPS Logger v3.1.0 the exportation folder is selectable (on Android 5+)
> I hope it helps.

Thank you, it helped a lot!

**Comment by GrazianoCapelli** [comment]
I'm glad it helped.
Thanks to this privacy change, you should start to see more folder/file picking request also from other apps.

I close this issue to keep our issues page clean. If you still need help, feel free to re-open it.
We added your interesting question to the _Frequently Asked Questions_ section for other users.
