### ISSUE TITLE
Web browser not recognized for online help

### ISSUE THREAD

**Issue by robertf** [BasicAirData/GPSLogger#183]
When I click on 'Online help' I get a message saying 'No Internet browser installed', but I have Firefox installed on my phone. I haven't seen anything in the documentation about how to cause a Web browser to be recognized. I assume that 'Internet browser' means a Web browser.

This is on a Samsung Galaxy A71running GPS Logger 3.1.4, Android 12 and Firefox 102.

**Comment by GrazianoCapelli** [comment]
Dear Robert,
first of all thanks for your reporting.

It could be an issue related to your specific phone, or a more generic one related to the [app visibility introduced in Android 11](https://developer.android.com/about/versions/11/privacy/package-visibility).

We'll do some tests with our test hardware, trying to reproduce the issue.
In parallel, we would be glad if you could do a test with the online help of another installed app, in order to verify if the problem is related to GPS Logger or to all the apps of your system.

Depending of this, we'll decide the right approach.

**Comment by robertf** [comment]
Thank you for your reply.

In OsmAnd, clicking on the app's links to GitHub and Facebook brought up Firefox. 

- Robert

**Comment by GrazianoCapelli** [comment]
Ok, thanks for yor test.
Could you please test also the links on the about screen of GPS Logger and the _Rate this App_ button on the same screen?

**Comment by robertf** [comment]
Both links on the About screen bring up Firefox. The 'Rate this App' button brings up a window asking whether I want to open with Google Play Store or Galaxy Store, and selecting Google Play Store takes me there.

**Comment by GrazianoCapelli** [comment]
Perfect, thanks also for the additional tests made!

**Comment by robertf** [comment]
Both links on the About screen bring up Firefox. The 'Rate this App' button brings up a window asking whether I want to open with Google Play Store or Galaxy Store, and selecting Google Play Store takes me there.

**Comment by robertf** [comment]
Sorry, I accidentally sent the comment again.
