### ISSUE TITLE
Buttons bug

### ISSUE THREAD

**Issue by ohayak** [BasicAirData/GPSLogger#26]
Hi,
I installed the app on a AVD api level 25, but on the Track app I can't see the buttons is that normal ?

**Comment by JLJu** [comment]
Hi Ohayak,
Thank you for your report. Can you send a screenshot? Any further info to reproduce the issue is very welcome (AVD, OS etc). That will help a lor.

**Comment by GrazianoCapelli** [comment]
Hi @ohayak,
At the app start (after the permissions request, in case of first run) you could see the following screen:
(GPSLogger v.2.1.5 at this moment)

![avd-api25](https://cloud.githubusercontent.com/assets/6907566/25294143/26c2664a-26de-11e7-93d7-a278cca796e3.png)

I can't reproduce your problem on my emulator (I attached the screenshot above, where all is ok).
The issue you report could also be caused by a problem in your local Android Studio configuration.

Please describe in a more detailed way your problem (or post a screenshot of your emulator), so that we'll have a good start point.

Cheers!

**Comment by GrazianoCapelli** [comment]
@ohayak ping?

**Comment by GrazianoCapelli** [comment]
@ohayak I close this issue, because of inactivity, to keep our issue tracker clean. If you still need help, please provide the information I requested and I'd be happy to reopen it.
