### ISSUE TITLE
App won't run in background

### ISSUE THREAD

**Issue by gusioo** [BasicAirData/GPSLogger#3]
I cannot minimize app with Home Button. App must be "on top" to register track.

Please consider add "run in background" option.

**Comment by GrazianoCapelli** [comment]
When the app is sent to background (pressing "back" or "home" button):
- if is recording, it should continue recording in background;
- else it should turn off the GPS (after 4 seconds);
We made several tests using different hardware.
Is the behaviour of the app on your phone different? In case, please, describe it in detail!

**Comment by gusioo** [comment]
Hi!

My scenario is:

- Turn on GPS Logger
- Wait for GPS signal.
- Start recording track (I use track points button).
- Send app to the background using a Home Key.
- Disable (not turn off) phone with a power key.

Now I wait a few seconds and turn on phone. After that I start GPS Logger and sometimes recording is stoppped and app searching GPS signal again.

My phone is: Alcatel One Touch Pop C7 (7041D)
Android Version: 4.4.2 (Kernel 3.4.67)

At this moment I cannot repeat this behaviour. Maybe it was an accident.

**Comment by GrazianoCapelli** [comment]
I hope it was an odd accident, but I'd grateful to know a couple of details in order to collect all the information about that strange behaviour and make some verifications:

1) After returning in GPS Logger the [trackpoints] button was still active (red) or it became inactive (grey)?
2) Waiting again the signal, the application continue recording or you need to press [trackpoints] button again?

I keep that issue open; in case your app falls again into that behaviour please report it!
In any case thanks for your reporting!

**Comment by gusioo** [comment]
Hi,

Thanks for helping me.

Ad.1 The button is grey and showing 0 points.
Ad.2 I need start again - app record a new track (the old one is saved)

Best regards,
Jacek.

**Comment by JLJu** [comment]
@gusioo,
Thank you  for your report. I will close the issue here. Please enter in contact if there are any further problems.
