### ISSUE TITLE
Maybe a little bug with the aviation and nautics measurement system

### ISSUE THREAD

**Issue by FineWithChocolate** [BasicAirData/GPSLogger#31]
Hello,

thank you for this great app without any unnecessary frills!

While browsing through this app (v2.1.7) I think I found a little bug with aviation / nautic measurement system: As unit for distance the nautical mile is implemented. And as units for speed I can choose between kn and mph. But the calculation for mph differes from kn. I think here is a mix of aviation / nautic and imperial system of measurement - for mph the statutory mile is used. In my opinion in aviation / nautics both kn and mph should be the same (based on the nautical mile).

I did not dare to change it because I do not know whether you implemented this intentionally that way. 

On the other hand I am not sure if mph is a used unit for speed in aviation / nautics. I think only kn is used.

Kind regards,
Gudrun

**Comment by GrazianoCapelli** [comment]
Hello Gudrun.
The units of measurement mainly used in aviation and nautics are:
- Distance in Nautical Miles (NM), where 1 NM = 1.852 km;
- Speed in Knots (kn), where 1 kn = 1 _nautical mile per hour_ = 1.852 km/h.

We implement the _statutory mile per hour_ (mph) as a choice (where 1 mph ~= 1.60934 km/h), because it's still used in a relevant amount of aircrafts to measure the speed. Ideally we should implement km/h too.

No bugs this time; we implement this intentionally because, sadly, the aviation/nautics world hasn't yet a real worldwide standard.

Thanks for your feedback!

**Comment by FineWithChocolate** [comment]
Hello Graziano,
thanks for your answer.

In case of mph based on the statutory mile would it not be better to use the statutory mile for the distance, too? 
km/h would be a good supplement. In that case I could imagine km as used for distance.

In my opinion speed should be calculable from distance and time. I think it is a little bit confusing when i.e. distance is displayed as nautical mile but speed is calculated with statutory mile.

**Comment by GrazianoCapelli** [comment]
> In case of mph based on the statutory mile would it not be better to use the statutory mile for the distance, too?

The app already has this ability. You can switch to Imperial system.

> In my opinion speed should be calculable from distance and time. I think it is a little bit confusing when i.e. distance is displayed as nautical mile but speed is calculated with statutory mile

I agree with you, because I'm not a pilot.
Unfortunately the aviation is often used to have convenient units of measurement, at the cost of mutual coherence. We added the Aerial / Nautical system of measurement in order to follow this point of view.
