### ISSUE TITLE
Thumbnails of Track Shapes

### ISSUE THREAD

**Issue by ulibuck** [BasicAirData/GPSLogger#80]
Hi
For documentation of my GPS logs I would like to use the thumbnails of the track shapes as shown on the tracklist tab.
Exploring my phone's storage I can't find those thumbnails.
Where are they located?
Alternatively, could they be exported?
BTW: I really like the GPSLogger App.
![Image_01](https://user-images.githubusercontent.com/19636871/64473450-415d9700-d167-11e9-9106-5e4b3134befc.jpg)

**Comment by GrazianoCapelli** [comment]
Every App saves its own data in a personal private folder on the Device Storage.
This folder is accessible by the App only, is included in the automatic Backup, and is automatically deleted when you uninstall the Application.
It is not possible to access it with any other App (no even using a USB connection) unless the device is not rooted.

GPS Logger, for example, creates a sub-folder on it to save the Thumbnails inside.
On my device, that folder is `/data/user/0/eu.basicairdata.graziano.gpslogger/files/Thumbnails`

This folder may be slightly different depending on the Device and Android Version.

To date we don't implemented a way to export the Thumbnails, because this image is generally not useful outside the Tracklist. In fact you can easily open a track with a real map and save a larger and cooler Screenshot of it.

Thanks for your feedback!

**Comment by ulibuck** [comment]
Thank you for your feedback and the detailed explanation.
Using gnunplot I now generate the thumbnails from the gpx file coordinates.
See attached for an example.
Purpose is a tracklist with some statistics, like total km, total time, etc.
Anyway, my case is solved.
![track-thumb](https://user-images.githubusercontent.com/19636871/64490912-494e3180-d262-11e9-8c8d-57cc20b64317.jpg)
