### ISSUE TITLE
question about EGM96 correction

### ISSUE THREAD

**Issue by 1stgongsin** [BasicAirData/GPSLogger#81]
Hi, I think purpose of EGM96 correction is to get accurate MSL(HAE) altitude.
and I'm curious whether smartphone gps chip receives "ellipsoidal height"  from satellite.
When I see raw NMEA $GPGGA sentence, 9th value is MSL height and 11th is geoid separation.
So, sum of these two value represents ellipsoidal height at the smartphone.

This app use this ellipsoidal height? and subtract EGM96 value from this ellipsoidal height ?
then where came from $GPGGA geoid value? satellite signal or device?

Thank you.

**Comment by GrazianoCapelli** [comment]
Hi,
Yes, the Purpose of the EGM96 Correction is exactly to get accurate Orthometric (MSL) Altitude.

The [$GPGGA](https://www.gpsinformation.org/dale/nmea.htm#GGA) sentence contains the _Altitude, Meters, above mean sea level_ (Orthometric Height) and the _Height of geoid (mean sea level) above WGS84 ellipsoid_ (the Geoid Correction applied by the Sensor).

Since every GPS sensor implements a different Geoid Model (some hardware use a simplified Geoid, some other doesn't implement any correction), we chosen to start from the ellipsoidal height and then apply the NGA/NASA EGM96 Geoid Correction to calculate the orthometric one.

The first time you activate the EGM96 Correction feature on GPS Logger, the application will download a file containing the [EGM Heights](https://earth-info.nga.mil/GandG/wgs84/gravitymod/egm96/egm96.html) from the NGA website (file size approx. 2 MB). The file is saved on the device's memory, no further internet connection is needed. The file is a binary 15 arc-minutes grid of Geoid Heights, that is used to calculate the right correction depending on FIX coordinates.

This way we can re-calculate the right Orthometric Altitude, regardless of the GPS Sensor.

_[Here](https://www.basicairdata.eu/projects/android/android-gps-logger/) in our Website you can find an informative paragraph about the characteristics and the usage of the EGM Grid._

_The calculation of a good GPS altitude is not trivial. If anyone wants to deepen the argument, [here](https://graticules.blogspot.com/2017/04/using-gps-logger-android-app-for-field.html) at the bottom of the page he can find a very interesting document ([PDF](https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxnZW9yZXN3ZWJ8Z3g6MWU3OWY0MDVkZGFkNGU5Ng)) with a good explanation of the vertical GPS accuracy (described at paragraph 3.2)._

**Comment by 1stgongsin** [comment]
Hi, GrazianoCapelli.
Thank you for your kindness and detailed explanation.
Have a good day.
