### ISSUE TITLE
Add more GPS update interval options

### ISSUE THREAD

**Issue by dylanbaker21** [BasicAirData/GPSLogger#82]
Three different scenarios

- Add more update interval options example 1 sec, 2 sec, 3 sec, 5 sec, 10 sec, 30 sec etc.
- Allow the user to set default intervals per mode of transportation.
- Allow the user to define the update interval. 

Any one or combination of these features would add a lot of flexibility. For example 3 seconds is the slowest interval right now but still generates too many data points for some uses.

**Comment by RiverMersey** [comment]
Even with a few thousand measurement points, the data files are still quite small.
For the purposes of accuracy / smoothing of the data, could we continue to record raw GPS data at 1 second intervals but add the option for the user of displaying the data in the suggested 1 sec, 2 sec, 3 sec, 5 sec, 10 sec, 30 sec etc. intervals?
We would then not be discarding the recorded data, we would be querying and displaying it in different ways

**Comment by GrazianoCapelli** [comment]
The main problem is that, if you request a FIX every 5 seconds (or at smaller frequency), the GPS turns off between the 2 consecutive requests, with a serious impact on Accuracy.

I think that a possible implementation could be the one suggested by @RiverMersey here above: keep high the GPS update frequency (1 - 3 sec.) and then discard redundant data when exporting.

As alternative, we could keep separated the _GPS Update Frequency_ and the _Recording Interval_, by adding an additional setting. This way the GPS can update at the right high frequency, while the recording process collects data more slowly.

**Comment by ygoe** [comment]
Are these intervals intended to be used a full day, with minimal battery impact? I've used another GPS logger on my old phone (Android 7) all day when travelling, with very little additional battery drain. That app is no longer available so I found this one. I've yet to try out how it affects the battery.

Generally I don't need the highest precision of 3 metres everywhere. In the old app, I could set intervals of I think 30 seconds, and it would wait for the accuracy to go below a certain threshold, I think it was 40 metres. That has produced good results and outdoors it usually used the GPS for just a few seconds. A warm fix doesn't take that long. There could be some smart setting that considers recent accuracy and tries to get similar results before logging the position. The biggest challenge here is to give up quickly (to save battery) when there is no GPS reception anymore, like going indoors, but don't miss when going out again. As a side note, the acceleration sensor (alone) is useless for that because it thinks the phone is steady when it's lying in a driving car... I had to disable that feature in the old app. If you wanted to use that sensor, be sure to check with GPS (for a limited time or at a reduced interval) whether the phone is really not moving.

I use this for geo-tagging of photos, mostly when walking around slowly, and as a general overview of the path I went.

**Comment by RiverMersey** [comment]
Hi,


Yes, this app can be adjusted on the "collection density" (distance) and the "interval" (time).


My limited understanding suggests that the battery performance also depends on the device that the app is being run on and wether the screen is constantly on or not.


On one occasion, I had the app constantly running, taking readings every second, with the screen on for about half of the time, on a Sony Xperia XA1 and it lasted for 10.6 hours until the battery died - which I was quite happy with. Had I have wanted it to last longer, I expect I could have charged it in use with a mobile power supply or power bank.


Once the GPS recording is complete, it is straight forward to email the various versions of the data as files from within the app - assuming WiFi or cellular coverage.


Get Outlook for Android

**Comment by phcorrigan** [comment]
I'd like to second the request for more interval options. For (most) photographers, a 10 second interval is more than adequate. I personally would like to see 10 sec., 30 sec., 1 min., 5 min., and 10 min., assuming those would save both storage space and battery life.

Thanks!

**Comment by kduvekot** [comment]
I personally also would like a "once-every-30-sec" update frequency .. or even "once-every-minute" .. and let it run in the background. For slow walking trips or sailing on a boat those intervals would be good enough for most people. So it's not about the size of the export or the number of recorded points, but mostly about battery savings.

Its mentioned that the GPS will turn off, so it would require some time to startup, get a good fix and accuracy .. and then record a position and shutdown again. What would be the expected battery saving for 30s/60s intervals ?

I am not a coder, but the code looks clean enough that it would just be a matter of adding 2 more entries in these arrays?
https://github.com/BasicAirData/GPSLogger/blob/master/app/src/main/res/values/arrays.xml#L48

with the value 30000 (30s) and 60000 (60s) ?

(and provide translations for it in the appropriate strings.xml files)

**Comment by GrazianoCapelli** [comment]
@kduvekot 
In terms of battery usage there is no advantage by turning on and off the GPS every 30 seconds, but the cost in terms of accuracy is very high. And, unfortunately, is not enough to add two entries: it needs to review the management of `LocationManager` and change the recording method.

I close this issue because we opened the #140, that will track the implementation of a new way to set the GPS Update interval: the Time Filter. The feature has been scheduled to be implemented on the next v3.1.0 release.

For further comment / suggestions / ideas, and to keep track of the implementation status, please use the issue #140.
