### ISSUE TITLE
Elevation resolution?

### ISSUE THREAD

**Issue by davehood86** [BasicAirData/GPSLogger#85]
The tracks I'm getting show elevation as integers. I suspect this is a characteristic of the device (Samsung A51), but just checking. Ok for individual elevations, but I like to log cumulative elevation gain or descent, and 1-meter noise makes that pretty much impossible.

**Comment by GrazianoCapelli** [comment]
When you record a track, GPS Logger calculates and stores the cumulative elevation gain and loss, that are fundamental to estimate for example the real _Distance_.
The two altitude values are discretized into jumps of at least 10m (depending on accuracy) in order to try to compensate the GPS errors and are used to calculate all the values that depend on altitudes.

Unfortunately you are right, most of the GPS sensors of the Android Devices are discretized to 1 meter, making almost meaningless these value of elevation gain and loss for the user.

For this reason we must calculate, but we chosen to not show them in GPS Logger.

For a good estimation of altitude gain and loss you should use a [Barometric Altimeter](https://www.basicairdata.eu/projects/barometric-altimeter/), but not all devices have the onboard barometer sensor.

**Comment by GrazianoCapelli** [comment]
@davehood86 I close this issue, because of inactivity, to keep our issue tracker clean.
If you still need help, We'll be happy to reopen it.

Have a nice Tracking!

**Comment by solomax** [comment]
Hello @GrazianoCapelli,

Is it possible this one can be re-opened? :)
I've just checked `kml` file (recorded by `GPSLogger  3.1.4`)
The altitude seems to have decimal part:

```
     83.20919051,54.94004003,125.862
     83.20921300,54.94009463,126.395
     83.20924939,54.94015062,126.993
     83.20928654,54.94020448,126.963
     83.20930244,54.94025959,127.386
     83.20931121,54.94031695,127.100
     83.20932472,54.94036955,126.911
```

Maybe total elevation can be estimated somehow? :)))

I'm using 3 sec update interval
Huawei P30 Pro
EMUI 12.0.0 (can't find Android version anymore :((( )
